# Generated by Django 5.2.4 on 2026-07-04 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="fa-graduation-cap",
                        help_text="FontAwesome icon class name",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="The question text")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice Single Answer"),
                            ("MultipleAnswers", "Multiple Choice Multiple Answers"),
                            ("TrueFalse", "True/False"),
                            ("FillBlank", "Fill in the Blank"),
                            ("Image", "Image Question"),
                            ("Programming", "Code/Programming Question"),
                            ("Paragraph", "Paragraph/Short Answer Question"),
                        ],
                        default="MCQ",
                        max_length=50,
                    ),
                ),
                (
                    "correct_answer_text",
                    models.TextField(
                        blank=True,
                        help_text="For Fill-in-Blank, Code, and Paragraph questions",
                        null=True,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Medium",
                        max_length=50,
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="URL or path to question image",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=1, help_text="Points awarded for a correct answer"
                    ),
                ),
                (
                    "negative_marks",
                    models.FloatField(
                        default=0.0, help_text="Points deducted for a wrong answer"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Explanation justifying the correct answer",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("place", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "password",
                    models.CharField(
                        help_text="Stored password hash at time of registration",
                        max_length=255,
                    ),
                ),
                (
                    "photo_url",
                    models.CharField(
                        blank=True,
                        default="/static/quiz/images/default-avatar.png",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        default="Computer Science",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        blank=True, default="Semester 1", max_length=50, null=True
                    ),
                ),
                (
                    "achievements",
                    models.TextField(
                        blank=True, help_text="Pills/List of student accomplishments"
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(help_text="The choice text", max_length=255)),
                (
                    "is_correct",
                    models.BooleanField(
                        default=False, help_text="Check if this is the correct answer"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="quiz.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Short description of the quiz"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True, default="2025-2026", max_length=50, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, default="Unit 1", max_length=50, null=True
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Medium",
                        max_length=50,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=60, help_text="Time limit in minutes"
                    ),
                ),
                (
                    "passing_score",
                    models.PositiveIntegerField(
                        default=60, help_text="Passing score percentage (0-100)"
                    ),
                ),
                (
                    "negative_marking",
                    models.BooleanField(
                        default=False, help_text="Enable negative marking for this quiz"
                    ),
                ),
                (
                    "negative_marks_per_question",
                    models.FloatField(
                        default=0.0,
                        help_text="Marks deducted for each incorrect answer",
                    ),
                ),
                (
                    "shuffle_questions",
                    models.BooleanField(
                        default=False,
                        help_text="Shuffle questions order for each attempt",
                    ),
                ),
                (
                    "shuffle_options",
                    models.BooleanField(
                        default=False,
                        help_text="Shuffle choices/options for each question",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum allowed attempts per student"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, help_text="Quiz availability start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quiz availability end date/deadline",
                        null=True,
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Backwards compatible deadline datetime",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Published", "Published"),
                            ("Archived", "Archived"),
                        ],
                        default="Draft",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="quiz.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
            ),
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                ("percentage", models.FloatField(default=0.0)),
                ("passed", models.BooleanField(default=False)),
                (
                    "time_taken",
                    models.PositiveIntegerField(
                        default=0, help_text="Time taken in seconds"
                    ),
                ),
                ("grade", models.CharField(default="F", max_length=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("InProgress", "InProgress"),
                            ("Completed", "Completed"),
                        ],
                        default="Completed",
                        max_length=50,
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="quiz.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="quiz.userregister",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="quiz.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quiz",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes",
                to="quiz.subject",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("notification_type", models.CharField(default="Info", max_length=50)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="quiz.userregister",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("percentage", models.FloatField(default=0.0)),
                (
                    "time_taken",
                    models.PositiveIntegerField(
                        default=0, help_text="Time taken in seconds"
                    ),
                ),
                ("accuracy", models.FloatField(default=0.0)),
                ("rank", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="quiz.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.userregister",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "time_taken"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_code", models.CharField(max_length=100, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.quizattempt",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="quiz.userregister",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_text",
                    models.TextField(
                        blank=True,
                        help_text="For FillBlank, Code, and Paragraph questions",
                        null=True,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="quiz.quizattempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.choice",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(
                        blank=True, related_name="multiple_responses", to="quiz.choice"
                    ),
                ),
            ],
            options={
                "ordering": ["question__id"],
            },
        ),
    ]
