# Generated by Django 5.2.4 on 2026-07-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="current_session_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the current session started",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userregister",
            name="last_active",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of the user's last request", null=True
            ),
        ),
    ]
