# Generated by Django 5.2.4 on 2026-07-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_quizsection_question_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Detailed exam instructions and conditions shown to students before starting",
                null=True,
            ),
        ),
    ]
