# Generated by Django 5.2.4 on 2026-07-05 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_quiz_instructions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="instructions",
        ),
        migrations.CreateModel(
            name="QuizCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="A specific rule or condition for this quiz",
                        max_length=500,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="quiz.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
