# Generated by Django 5.2.4 on 2026-07-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_remove_quiz_instructions_quizcondition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizsection",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="userresponse",
            name="is_marked_for_review",
            field=models.BooleanField(default=False),
        ),
    ]
