# Generated by Django 5.2.4 on 2026-07-07 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_alter_quizsection_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_class",
                    models.CharField(
                        default="bi-star-fill",
                        help_text="Bootstrap icon class",
                        max_length=100,
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False, help_text="Highlight this plan as most popular"
                    ),
                ),
                (
                    "price_1m",
                    models.PositiveIntegerField(
                        default=0, help_text="Price for 1 Month in INR"
                    ),
                ),
                (
                    "price_6m",
                    models.PositiveIntegerField(
                        default=0, help_text="Price for 6 Months in INR"
                    ),
                ),
                (
                    "price_12m",
                    models.PositiveIntegerField(
                        default=0, help_text="Price for 1 Year in INR"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "is_included",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, shows as a disabled feature with an X",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="quiz.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
