# Generated by Django 5.2.4 on 2026-07-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0007_subscriptionplan_subscriptionfeature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="price_12m",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="price_1m",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="price_6m",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="price",
            field=models.PositiveIntegerField(default=0, help_text="Price in INR"),
        ),
    ]
