# Generated by Django 5.2.4 on 2026-07-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0008_remove_subscriptionplan_price_12m_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=30, help_text="Duration in days (0 for lifetime)"
            ),
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, help_text="Null means lifetime access", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Mock transaction ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("amount_paid", models.PositiveIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="quiz.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="quiz.userregister",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
