# Generated by Django 5.2.4 on 2026-07-07 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0009_subscriptionplan_duration_days_usersubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
