# Generated by Django 5.2.4 on 2026-07-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0010_alter_usersubscription_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='department',
            new_name='target_exam',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='semester',
            new_name='education_qualification',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='achievements',
            new_name='preparation_stage',
        ),
        migrations.AlterField(
            model_name='userregister',
            name='target_exam',
            field=models.CharField(blank=True, default='UPSC', help_text='e.g. UPSC, SSC, Banking', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='education_qualification',
            field=models.CharField(blank=True, default='Graduate', help_text='e.g. Graduate, Post Graduate', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='preparation_stage',
            field=models.TextField(blank=True, help_text='e.g. Beginner, 1 Year, etc.'),
        ),
    ]
