# Generated by Django 5.2.15 on 2026-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0011_rename_user_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_or_email", models.CharField(max_length=255)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="userregister",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
